/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#afcbd8",
        "on-surface-variant": "#434750",
        "on-primary-fixed": "#001a42",
        "surface-container": "#eceeef",
        "tertiary-container": "#1a3540",
        "surface-container-high": "#e6e8e9",
        "on-primary-container": "#7999dc",
        background: "#f8f9fa",
        primary: "#001b44",
        "on-secondary-fixed": "#002113",
        "on-secondary-container": "#00714b",
        "primary-fixed-dim": "#aec6ff",
        "surface-tint": "#3c5d9c",
        "secondary-fixed": "#8df7c1",
        "error-container": "#ffdad6",
        surface: "#f8f9fa",
        "surface-dim": "#d8dadb",
        "inverse-primary": "#aec6ff",
        "tertiary-fixed": "#cbe7f5",
        "on-background": "#191c1d",
        "surface-container-highest": "#e1e3e4",
        "primary-fixed": "#d8e2ff",
        "on-secondary-fixed-variant": "#005235",
        "primary-container": "#002f6c",
        "on-tertiary-fixed": "#021f29",
        "on-primary-fixed-variant": "#224583",
        "inverse-surface": "#2e3132",
        tertiary: "#03202a",
        "surface-variant": "#e1e3e4",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#304a55",
        "secondary-dim": "#005f48",
        "secondary-fixed-dim": "#71dba6",
        "tertiary-dim": "#903526",
        secondary: "#006c47",
        "on-surface": "#191c1d",
        "primary-dim": "#005498",
        "surface-container-low": "#f2f4f5",
        "outline-variant": "#c4c6d2",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eff1f2",
        "surface-bright": "#f8fafb",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "secondary-container": "#8af5be",
        "on-tertiary-container": "#839eaa",
        "on-tertiary": "#ffffff",
        "error-dim": "#70030f",
        outline: "#747781",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        display: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      animation: {
        "bounce-slow": "bounce 3s infinite",
        "pulse-soft": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        float: "float 3s ease-in-out infinite",
        "fade-in-up": "fadeInUp 0.6s ease-out forwards",
        "postit-enter": "postitEnter 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "pin-drop": "pinDrop 0.4s cubic-bezier(0.34, 1.56, 0.64, 1) forwards",
        "megaphone-shake": "megaphoneShake 2.5s ease-in-out infinite",
        "wave-out": "waveOut 2s ease-in-out infinite",
        "blink-dot": "blinkDot 1.4s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        postitEnter: {
          "0%": { opacity: "0", transform: "rotate(-6deg) scale(0.85) translateY(20px)" },
          "100%": { opacity: "1", transform: "rotate(-2deg) scale(1) translateY(0)" },
        },
        pinDrop: {
          "0%": { opacity: "0", transform: "translateY(-12px) scale(0.7)" },
          "100%": { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        megaphoneShake: {
          "0%, 100%": { transform: "rotate(0deg) scale(1)" },
          "10%": { transform: "rotate(-12deg) scale(1.1)" },
          "20%": { transform: "rotate(8deg) scale(1.1)" },
          "30%": { transform: "rotate(-6deg) scale(1.05)" },
          "40%": { transform: "rotate(4deg) scale(1.05)" },
          "50%": { transform: "rotate(0deg) scale(1)" },
        },
        waveOut: {
          "0%": { transform: "scale(0.9)", opacity: "0.6" },
          "60%": { transform: "scale(1.8)", opacity: "0" },
          "100%": { transform: "scale(1.8)", opacity: "0" },
        },
        blinkDot: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.2" },
        },
      },
    },
  },
  plugins: [],
}
